jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Git
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "your-email@example.com"
      
      - name: Pull remote changes
        run: git pull --rebase https://huggingface.co/spaces/Chandan1010/Math_GPT_LLM main
      
      - name: Push changes
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://huggingface.co/spaces/Chandan1010/Math_GPT_LLM main
